services:
  - type: web
    name: xfourtune-roulette
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PYTHONPATH
        value: .
    disk:
      name: sqlite-disk
      mountPath: /opt/render/project/src
      sizeGB: 1
